### ISSUE TITLE
Sunday tasks

### ISSUE THREAD

**Issue by MAlbertZ** [rabble/allofus#1] opened 2024-12-07 02:49 UTC
Things to do Sunday:

Put in box for user to add their email address to our email list—still to be created.

Add graphics for aesthetic appeal - only from the graphics directory: https://drive.google.com/drive/u/0/folders/18CYVwCfvxNMhdENaIBVvl7DUznrjRD8O
I guess on each plain text page, like home, about, conveners, etc.

Add button “My Organization Is Interested in Joining” with explanation:
Apply to add your organization to the All of US Directory
Leads to a page Titled Add My Organization, with text area, and with form with the following fields:

Org Name
Email of Person Requesting Membership
Org Email
Location (National and/or City for in person volunteers
Org Projects (that could currently utilize volunteer help)
Org Description (however long you choose to facilitate users knowing if it makes sense to volunteer)
Org Web link

When submitted this form goes to site address—sender gets form letter acknowledging receipt…

When accepted or rejected emails goes to applier’s email…text Sunday…but…
If accepted the information goes to what will be their unique page to populate part of their creation form…and they get a single ID and Passwotd and the page creation/admin url, included.

the site itself also needs a organization member sign-in perhaps called “Admin Organization Page” which require ID and PW and goes to the Org Create/Admin page/form already populated with their info…

Add the text for the About Page - we did this, but it is now gone, so here it is again (‘the ** surrounds bolted text)

About Page

**What Is Our Goal?**
All of Us is designed to help people get more directly involved in progressive and left efforts throughout the U.S. confronting the MAGA program. The tool we offer can connect you with groups working on many issues as part of a larger social change movement aimed at building toward a better future for everyone.

**What Do We Do?**
We provide a directory designed to help people and organizations find each other. Organizations describe their work and what need they have for volunteers and new members. Individuals then search the directory to find an organization that they want to connect with, filtering for:

* location,
* area of interest, and
* the kinds of experience and knowledge they have to offer.
⠀
**What Organizations Are Included In The Directory?**
Broadly speaking, The All Of US member groups are grassroots-friendly, progressive-leaning, non-commercial, and non-sectarian; they seek and give solidarity; they are welcoming and value participation. They are eager to reply to requests from people who want to join or to help them, and they are able to welcome and involve people who would fit well. Do you want to add your organization to the directory? **Start here.**

**What Individuals Use the Directory?**
Anyone who wants to connect with others to address concerns about what is happening in the U.S. – whether in response to Trump or MAGA-ism or in response to the general need to improve life in our communities, stop negative policies, win positive gains, and build with others towards a better world. Do you want to try searching the database? **Start here.**

**Who Decides What’s Included?**
We want users to find what they seek. Thus we work with organizations to be forthright in presenting themselves, their aims, their values, and their allegiances for assessment via their All of US unique pages. Have questions? **Contact us.**

**Subtext:** All sects, whiners, complainers, no good counterproductive my way or the highway types—steer clear.

On testimonials page change “‘hear” to “Comments”

Add “Project History” to the drop down under About to a page for text, coming

Create page Titled “Create Your Unique Organization Directory Page” that needs the id and password to access (which they get if staff accepts their first form…)
This page will have some text and also the following form — where the asterisked entries are required…
And some fields are, ideally, already filled with material from their prior application form.

Org Name*
Email of Person Requesting Membership*
Org Email*
Logo/Graphic
Location (National and/or City for in person volunteers)*
Focus Areas (choose as many as apply from pull down list, or…)*
Engagement Types (what the org would welcome/benefit from, choose as many as apply from pull-down list or…)*
Org Projects (that could currently utilize volunteer help)
Org Description (however long you choose to facilitate users knowing if it makes sense to volunteer)
Org Web link*
Org Volunteer Link
Org Join link
Org Social Media links*
Toggle to include Social Media Feeds…

When their Org Page is accepted they get an auto email telling them and an Action Network like referral tool.

Whenever a unique org page is submitted or updated staff get an email notice to vet it…

**Comment by rabble** [comment] 2024-12-08 21:56
Dupe of #2

**Closed as completed by rabble** 2024-12-08 21:56 UTC
